$(document).ready(function() {


  // Variables and constants needed by Handlebars to create Template
  const source = $("#card-template").html();
  const template = Handlebars.compile(source);

  // ------------- PRINTING MUSIC DISCS ON SCREEN USING TEMPLATE --------------

  // This code should be run only for "vers-ajax" (to print on screen the music discs in the "index.html" file)

  /*
  // OPTION 1 - Checking if the tag "cards container" has children tags in its html
  if($('#cards-container').children().length === 0) {
  }
  */

  /*
  // OPTION 2 - Checking if the ID given to the tag "body" only in the vers-ajax exists (if it exists, it has a "length")
  */
  if($('#vers-ajax').length) {
    // AJAX call to get all the discs (no filters)
    $.ajax({
      url: '../discs.php',
      method: 'GET',
      success: function(results) {
        // Creating an empty array for the music genres
        let genres_list = [];
        // Scrolling the array 'results' generated by the Ajax call
        for (let i = 0; i < results.length; i++) {
          // Accessing the properties of the objects in 'results'
          var context = {
            'poster': results[i].poster,
            'title': results[i].title,
            'author': results[i].author,
            'year': results[i].year,
          }
          // Storing the data in a variable and printing them on screen
          var html = template(context);
          $('#cards-container').append(html);
          // Storing the genre of the current disc in a variable
          let current_genre = results[i].genre;
          // Checking that the genre is not already in the genres array
          if(!genres_list.includes(current_genre)) {
            genres_list.push(current_genre);
          }
        } // End of the "for" loop
        // Scrolling the array of genres
        for (let i = 0; i < genres_list.length; i++) {
          $('#select-genre').append(`
            <option value="${genres_list[i]}">${genres_list[i]}</option>
            `);
        }
      },
      error: function() {
        console.log('ERROR. Sorry, something went wrong!');
      },
    });
  }

  // ---------------------------- FILTER BY GENRE ----------------------------

  // Intercepting the user's select choice
  $('#select-genre').change(function() {
    // Emptying the music discs cards container
    $('#cards-container').empty();
    // Storing the value of the selected genre in a variable
    let selected_genre = $(this).val();

    // AJAX call to get only the discs with the selected genre (genre filter)
    $.ajax({
      url: '../discs.php',
      method: 'GET',
      data: {
        genre: selected_genre,  // This data is needed to be passed to the PHP
      },
      success: function(results) {
        // Scrolling the array 'results' generated by the Ajax call
        for (let i = 0; i < results.length; i++) {
          // Accessing the properties of the objects in 'results'
          var context = {
            'poster': results[i].poster,
            'title': results[i].title,
            'author': results[i].author,
            'year': results[i].year,
          }
          // Storing the data in a variable and printing them on screen
          var html = template(context);
          $('#cards-container').append(html);
        }
      },
      error: function() {
        console.log('ERROR. Sorry, something went wrong!');
      },
    }); // End of AJAX call
  });
});
